In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import ttest_ind, shapiro, levene, mannwhitneyu
from scipy.stats import chi2_contingency
from fuzzywuzzy import process

# remov column limit
pd.set_option('display.max_columns', None)

/Users/caiocastro/Padrao/GitHub/PJ_Interno/myenv/lib/python3.9/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [24]:
df = pd.read_csv('bases/PAC_CIV.csv')

/var/folders/j4/tygk56x10hjb9g65vzjwkljc0000gn/T/ipykernel_5344/3732211914.py:1: DtypeWarning: Columns (0,1,2,3,4,6,7,8,9,10,11,12,13,14,15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('bases/PAC_NTEC.csv')

In [25]:
df

,Semana,Empresa,Setor do LinkedIn,Número de Funcionários,Nome,Cargo,Email,Prospecção,STATUS,Cadência,Hunter,Portfólio,Valor,OUT BIRDS - Semana 1 (12/04/2023),12/4/2023,12/10/2023,Ciclo
0,OUT BIRDS - Semana 6 (01/08/2024),MatchVerse,Education,11-50,Gabriel Vinicius,Founder/Co-founder,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 2 (12/11/2023),12/11/2023,12/17/2023,#REF!
1,OUT BIRDS - Semana 8 (01/22/2024),Movidaria,Education,11-50,Leticia Casavella,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 3 (12/18/2023),12/18/2023,12/24/2023,#REF!
2,OUT BIRDS - Semana 8 (01/22/2024),Movidaria,Education,11-50,Leticia Casavella,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 4 (12/25/2023),12/25/2023,12/31/2023,#REF!
3,OUT BIRDS - Semana 8 (01/22/2024),Movidaria,Education,11-50,Alcir Miguel Jr.,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 5 (01/01/2024),1/1/2024,1/7/2024,#REF!
4,OUT BIRDS - Semana 8 (01/22/2024),Movidaria,Education,11-50,Alcir Miguel Jr.,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 6 (01/08/2024),1/8/2024,1/14/2024,#REF!
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48631,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48632,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48633,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48634,NaN,NaN,NaN,NaN,NaN,Diretor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
# Write a regex expression to capture the date bewteen the parenthesis in "Semana"

df['Semana'] = df['Semana'].str.extract(r'\((\d{2}/\d{2}/\d{4})\)')

df

,Semana,Empresa,Setor do LinkedIn,Número de Funcionários,Nome,Cargo,Email,Prospecção,STATUS,Cadência,Hunter,Portfólio,Valor,OUT BIRDS - Semana 1 (12/04/2023),12/4/2023,12/10/2023,Ciclo
0,01/08/2024,MatchVerse,Education,11-50,Gabriel Vinicius,Founder/Co-founder,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 2 (12/11/2023),12/11/2023,12/17/2023,#REF!
1,01/22/2024,Movidaria,Education,11-50,Leticia Casavella,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 3 (12/18/2023),12/18/2023,12/24/2023,#REF!
2,01/22/2024,Movidaria,Education,11-50,Leticia Casavella,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 4 (12/25/2023),12/25/2023,12/31/2023,#REF!
3,01/22/2024,Movidaria,Education,11-50,Alcir Miguel Jr.,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 5 (01/01/2024),1/1/2024,1/7/2024,#REF!
4,01/22/2024,Movidaria,Education,11-50,Alcir Miguel Jr.,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 6 (01/08/2024),1/8/2024,1/14/2024,#REF!
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48631,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48632,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48633,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48634,NaN,NaN,NaN,NaN,NaN,Diretor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
# Convert the "Semana" column to datetime. It is d/m/y format

# Function to convert mixed date formats
def parse_dates(date_str):
    for fmt in ('%d/%m/%Y', '%m/%d/%Y'):
        try:
            return pd.to_datetime(date_str, format=fmt)
        except ValueError:
            continue
    return pd.NaT


df['Semana'] = df['Semana'].apply(parse_dates)

In [28]:
df

,Semana,Empresa,Setor do LinkedIn,Número de Funcionários,Nome,Cargo,Email,Prospecção,STATUS,Cadência,Hunter,Portfólio,Valor,OUT BIRDS - Semana 1 (12/04/2023),12/4/2023,12/10/2023,Ciclo
0,2024-08-01,MatchVerse,Education,11-50,Gabriel Vinicius,Founder/Co-founder,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 2 (12/11/2023),12/11/2023,12/17/2023,#REF!
1,2024-01-22,Movidaria,Education,11-50,Leticia Casavella,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 3 (12/18/2023),12/18/2023,12/24/2023,#REF!
2,2024-01-22,Movidaria,Education,11-50,Leticia Casavella,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 4 (12/25/2023),12/25/2023,12/31/2023,#REF!
3,2024-01-22,Movidaria,Education,11-50,Alcir Miguel Jr.,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 5 (01/01/2024),1/1/2024,1/7/2024,#REF!
4,2024-01-22,Movidaria,Education,11-50,Alcir Miguel Jr.,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 6 (01/08/2024),1/8/2024,1/14/2024,#REF!
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48630,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48631,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48632,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48633,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48634,NaT,NaN,NaN,NaN,NaN,Diretor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
# Only get the rows where the "Semana" column is greater than 2023-01-01

df = df[df['Semana'] > '2023-01-01']

In [30]:
df

,Semana,Empresa,Setor do LinkedIn,Número de Funcionários,Nome,Cargo,Email,Prospecção,STATUS,Cadência,Hunter,Portfólio,Valor,OUT BIRDS - Semana 1 (12/04/2023),12/4/2023,12/10/2023,Ciclo
0,2024-08-01,MatchVerse,Education,11-50,Gabriel Vinicius,Founder/Co-founder,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 2 (12/11/2023),12/11/2023,12/17/2023,#REF!
1,2024-01-22,Movidaria,Education,11-50,Leticia Casavella,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 3 (12/18/2023),12/18/2023,12/24/2023,#REF!
2,2024-01-22,Movidaria,Education,11-50,Leticia Casavella,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 4 (12/25/2023),12/25/2023,12/31/2023,#REF!
3,2024-01-22,Movidaria,Education,11-50,Alcir Miguel Jr.,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 5 (01/01/2024),1/1/2024,1/7/2024,#REF!
4,2024-01-22,Movidaria,Education,11-50,Alcir Miguel Jr.,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App,NaN,OUT BIRDS - Semana 6 (01/08/2024),1/8/2024,1/14/2024,#REF!
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3858,2024-07-29,EVO,financial services,11-50,Andre Pacheco,Gerente de Operações,andre.pacheco@evo.com.br,E-mail,Não Respondeu,NaN,luizhenrique.silva,Product Discovery,NaN,NaN,NaN,NaN,NaN
3859,2024-07-29,Ore Investments,financial services,11-50,Eduardo Cardoso,Sócio,eduardo.cardoso@oreinvestments.com.br,E-mail,Não Respondeu,NaN,luizhenrique.silva,Product Discovery,NaN,NaN,NaN,NaN,NaN
3860,2024-07-29,Ore Investments,financial services,11-50,Ricardo Lopes,Sócio,ricardo.lopes@oreinvestments.com.br,E-mail,Não Respondeu,NaN,luizhenrique.silva,Product Discovery,NaN,NaN,NaN,NaN,NaN
3861,2024-07-29,Ore Investments,financial services,11-50,Thiago Bonas,Sócio,thiago.bonas@oreinvestments.com.br,E-mail,Não Respondeu,NaN,luizhenrique.silva,Product Discovery,NaN,NaN,NaN,NaN,NaN
3862,2024-07-29,Ore Investments,financial services,11-50,Mauro Barros,CEO,mauro@ore.investments,E-mail,Não Respondeu,NaN,luizhenrique.silva,Product Discovery,NaN,NaN,NaN,NaN,NaN

In [31]:
# Count different portfolios

df['Portfólio'].value_counts()

Portfólio
Dev - Site           2918
Dev - App             693
Product Discovery     224
Concepcção             10
Não tem demanda         2
Name: count, dtype: int64

In [32]:
df.dropna(subset=['Prospecção'], inplace=True)

df['Prospecção'] = df['Prospecção'].apply(lambda x: process.extractOne(x, ['E-mail', 'LinkedIn'])[0])

/var/folders/j4/tygk56x10hjb9g65vzjwkljc0000gn/T/ipykernel_5344/2837389257.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=['Prospecção'], inplace=True)
/var/folders/j4/tygk56x10hjb9g65vzjwkljc0000gn/T/ipykernel_5344/2837389257.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Prospecção'] = df['Prospecção'].apply(lambda x: process.extractOne(x, ['E-mail', 'LinkedIn'])[0])

In [34]:
# Drop the last 5 columns

df.drop(df.columns[-5:], axis=1, inplace=True)

/var/folders/j4/tygk56x10hjb9g65vzjwkljc0000gn/T/ipykernel_5344/2756943837.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(df.columns[-5:], axis=1, inplace=True)

In [35]:
df

,Semana,Empresa,Setor do LinkedIn,Número de Funcionários,Nome,Cargo,Email,Prospecção,STATUS,Cadência,Hunter,Portfólio
0,2024-08-01,MatchVerse,Education,11-50,Gabriel Vinicius,Founder/Co-founder,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App
1,2024-01-22,Movidaria,Education,11-50,Leticia Casavella,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App
2,2024-01-22,Movidaria,Education,11-50,Leticia Casavella,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App
3,2024-01-22,Movidaria,Education,11-50,Alcir Miguel Jr.,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App
4,2024-01-22,Movidaria,Education,11-50,Alcir Miguel Jr.,Sócio,email@example.com,E-mail,Não Respondeu,NaN,gustavo.baeta,Dev - App
...,...,...,...,...,...,...,...,...,...,...,...,...
3858,2024-07-29,EVO,financial services,11-50,Andre Pacheco,Gerente de Operações,andre.pacheco@evo.com.br,E-mail,Não Respondeu,NaN,luizhenrique.silva,Product Discovery
3859,2024-07-29,Ore Investments,financial services,11-50,Eduardo Cardoso,Sócio,eduardo.cardoso@oreinvestments.com.br,E-mail,Não Respondeu,NaN,luizhenrique.silva,Product Discovery
3860,2024-07-29,Ore Investments,financial services,11-50,Ricardo Lopes,Sócio,ricardo.lopes@oreinvestments.com.br,E-mail,Não Respondeu,NaN,luizhenrique.silva,Product Discovery
3861,2024-07-29,Ore Investments,financial services,11-50,Thiago Bonas,Sócio,thiago.bonas@oreinvestments.com.br,E-mail,Não Respondeu,NaN,luizhenrique.silva,Product Discovery
3862,2024-07-29,Ore Investments,financial services,11-50,Mauro Barros,CEO,mauro@ore.investments,E-mail,Não Respondeu,NaN,luizhenrique.silva,Product Discovery

In [36]:
# download the df to a csv file

df.to_csv('bases/PAC_NTECcleaned.csv', index=False)